### ISSUE TITLE
Redmine 3.x compatibility

### ISSUE THREAD

**Issue by ppoektos** [sukima/redmine_equipment_status_viewer#71]

**Comment by sukima** [comment]
I can no longer maintain this code on my own. I need contributions to make any effort worth while. I no longer use this in my day to day work and have no intention to provide support all on my own. This project follows a very loose contribution process in that a simple pull request is all that is needed to be given commit access. If you want a feature or have it upgraded to the latest version of Redmine or Rails I ask that you make a Pull Request with that change so that others can also benefit.

Redmine Equipment Status Viewer is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
